window.IMPORTED_GERMAN_TOPICS = [
  {
    id: "arbeitsmodelle-und-stellenmarkt",
    number: 3,
    title: "Форми роботи та ринок праці",
    promptZh:
      "这一组把工作形式、合同状态和招聘用语放在同一条线里学。这样你在看职位信息、描述工作条件和比较岗位时，会更容易形成稳定表达。",
    promptEn:
      "This topic connects job formats, contract conditions and job-ad vocabulary so you can talk about work arrangements more naturally.",
    sections: [
      {
        id: "arbeitsformen-und-zeiten",
        tabLabel: "Форми роботи",
        tabLabelZh: "工作形式",
        sectionTitle: "A. Форми роботи й час",
        sectionTitleZh: "工作形式与时间安排",
        words: [
          ["навчання за фахом", "professional qualification for a job", "职业培训"],
          ["декретна відпустка", "time away from work after the birth of a child", "育儿假"],
          ["підробіток", "small part-time job with low income", "低收入兼职"],
          ["практика", "practical work to learn from experience", "实习"],
          ["мовні навички", "ability to use a language", "语言能力"],
          ["посада", "offered work position", "职位"],
          ["неповний робочий день", "work with reduced hours", "兼职"],
          ["повний робочий день", "work with the full weekly schedule", "全职"],
          ["безробітний", "without a job or employment", "失业的"],
          ["строковий", "valid only for a limited time", "有期限的"],
          ["безстроковий", "without a fixed end date", "无固定期限的"],
          ["зараз", "at the moment or currently", "目前"],
          ["години на тиждень", "number of working hours in a week", "每周小时数"]
        ]
      },
      {
        id: "betrieb-und-bedingungen",
        tabLabel: "Умови",
        tabLabelZh: "工作条件",
        sectionTitle: "B. Компанія та умови",
        sectionTitleZh: "企业、条件与招聘用语",
        words: [
          ["робоча атмосфера", "atmosphere at the workplace", "工作氛围"],
          ["робочий час", "time during which one works", "工作时间"],
          ["професійна освіта", "training for a certain profession", "职业培训"],
          ["досвід роботи", "practical experience in a job", "工作经验"],
          ["підприємство", "company or business", "企业"],
          ["заява на роботу", "application documents for a position", "求职申请"],
          ["документи для заявки", "all documents for an application", "申请材料"],
          ["оплата", "salary or payment for work", "薪资"],
          ["клієнт", "person or company buying something", "客户"],
          ["співробітник", "person who works in a company", "员工"],
          ["погодинна оплата", "payment per hour of work", "时薪"],
          ["команда", "group of people working together", "团队"],
          ["заміна", "person or arrangement that replaces someone", "替代；代理"],
          ["умова", "requirement that must be fulfilled", "条件"],
          ["підвищення кваліфікації", "professional learning after initial training", "进修；继续教育"],
          ["агентство тимчасової зайнятості", "company for temporary job placements", "劳务派遣公司"],
          ["подаватися", "to submit an application", "申请（工作）"],
          ["пропонувати", "to make something available", "提供"],
          ["завершений", "successfully completed", "完成的"],
          ["працевлаштований", "employed or in work", "在职的"],
          ["сучасний", "modern and up to date", "现代的"],
          ["сталий", "sustainable and mindful for the long term", "可持续的"],
          ["екологічний", "considering the environment", "生态的"],
          ["самостійний", "working independently or self-employed", "自主的；个体经营的"],
          ["повний", "without missing parts", "完整的"],
          ["бажаний", "especially desired", "理想的；可取的"],
          ["ч/ж/і", "job ad abbreviation for male, female and inclusive", "职位标注：男性 / 女性 / 多元", "乌克兰语站里保留为性别包容职位标识说明。"],
          ["відразу", "directly from now on", "立即；从现在开始"]
        ]
      },
      {
        id: "fachkraft-und-stellenprofil",
        tabLabel: "Профіль",
        tabLabelZh: "岗位画像",
        sectionTitle: "C. Профіль кандидата",
        sectionTitleZh: "岗位画像与招聘偏好",
        words: [
          ["фахівець", "qualified person in a profession", "专业人员"],
          ["додаткова робота", "additional work next to the main job", "兼职"],
          ["кваліфікація", "professional requirement for a job", "资格；资历"],
          ["регіон", "area or region", "地区"],
          ["основа для переговорів", "starting basis for negotiations", "谈判基础"],
          ["бажана зарплата до оподаткування", "desired salary before tax", "期望税前工资"],
          ["письмове звернення", "written message or application letter", "来信；申请信"],
          ["зв'язатися", "to make contact with someone", "联系"],
          ["брати на себе", "to take over a task", "承担；接手"],
          ["переважний", "preferred or given priority", "优先的"],
          ["залучений", "active and motivated", "积极投入的"],
          ["гнучкий", "easily adaptable to new situations", "灵活的"],
          ["ґрунтовний", "well founded and solid", "扎实的"],
          ["вигідний", "advantageous or inexpensive", "有利的；便宜的"],
          ["багаторічний", "lasting over many years", "多年的"],
          ["професійний", "expert and correct in work", "专业的"],
          ["уважний", "careful and exact", "仔细的"],
          ["орієнтований на команду", "focused on teamwork", "有团队精神的"],
          ["наявний", "available or existing", "现有的"],
          ["надійний", "someone or something you can rely on", "可靠的"],
          ["якомога більше", "as much as possible", "尽可能"]
        ]
      }
    ]
  },
  {
    id: "anerkennung-und-bewerbung",
    number: 4,
    title: "Визнання та подання заявки",
    promptZh:
      "这一组把资格认证和求职表达放在一起。现实里常常是先证明自己的资格，再写申请、准备面试、谈入职条件。",
    promptEn:
      "This topic combines qualification recognition with application language, because those steps often appear together in real life.",
    sections: [
      {
        id: "anerkennung-und-nachweise",
        tabLabel: "Визнання",
        tabLabelZh: "资格认证",
        sectionTitle: "A. Визнання та підтвердження",
        sectionTitleZh: "资格认证与证明材料",
        words: [
          ["визнання", "official confirmation or acceptance", "认可"],
          ["визнання професії", "official recognition of a professional qualification", "职业资格认证"],
          ["заява", "formal request to an authority", "申请"],
          ["консультаційний центр", "place for advice and help", "咨询机构"],
          ["професійний диплом", "official qualification for a profession", "职业资格证书"],
          ["тривалість", "length of a time span", "时长"],
          ["форма", "written input document", "表格"],
          ["зарплата", "fixed salary per month", "工资"],
          ["нічна зміна", "work during the night", "夜班"],
          ["підтвердження", "official proof or evidence", "证明"],
          ["доглядальник", "person working in care", "护理人员"],
          ["іспит", "official test", "考试"],
          ["переклад", "transfer into another language", "翻译"],
          ["свідоцтво", "official document about achievement or completion", "证书"],
          ["визнавати", "to accept officially", "承认；认可"],
          ["наймати", "to take someone into work", "雇用"],
          ["допомагати", "to give support", "帮助"],
          ["впоратися", "to manage successfully", "完成；做到"],
          ["заробляти", "to receive money through work", "赚取"],
          ["чуйний", "ready to help", "乐于助人的"],
          ["ввічливий", "friendly and respectful", "礼貌的"],
          ["компетентний", "professionally capable and secure", "有能力的；专业的"]
        ]
      },
      {
        id: "anschreiben-und-interview",
        tabLabel: "Заявка",
        tabLabelZh: "求职沟通",
        sectionTitle: "B. Лист і співбесіда",
        sectionTitleZh: "求职信、面试与表达",
        words: [
          ["супровідний лист", "written text for a job application", "求职信"],
          ["запрошення", "request to come to an appointment", "邀请"],
          ["дата початку роботи", "point in time when work starts", "入职时间"],
          ["досвід", "knowledge from practical experience", "经验"],
          ["гнучкість", "ability to adapt well", "灵活性"],
          ["зацікавлення", "interest or curiosity", "兴趣"],
          ["компетенція", "professional ability", "能力"],
          ["м'які навички", "personal and social skills", "软技能"],
          ["уміння працювати в команді", "ability to cooperate", "团队合作能力"],
          ["співбесіда", "conversation for a job application", "面试"],
          ["надійність", "quality of being reliable", "可靠性"],
          ["звертати увагу на", "to pay attention to something", "注意"],
          ["починати в", "to begin at a place or with someone", "从……开始"],
          ["подаватися на", "to apply for a position", "申请（职位）"],
          ["просити про", "to ask politely for something", "请求"],
          ["здобувати досвід", "to gain practical experience", "积累经验"],
          ["радіти з", "to be happy about something", "对……感到高兴"],
          ["відвідувати курс", "to take part in a course", "参加课程"],
          ["пасувати до", "to fit something well", "适合"],
          ["працювати як", "to work in the role of", "从事……工作"],
          ["бути у розпорядженні", "to be available", "可供使用；有空"],
          ["співпрацювати з", "to work together with", "与……合作"],
          ["оголошений", "officially published", "已发布的（职位）"],
          ["успішний", "with a good result", "成功的"],
          ["необхідний", "necessary", "必要的"],
          ["якнайшвидше", "as early as possible", "尽早"],
          ["самостійний", "working independently", "独立的"],
          ["командний", "good at working in a team", "有团队合作能力的"],
          ["гнучкий у часі", "adaptable in scheduling", "时间灵活的"]
        ]
      }
    ]
  },
  {
    id: "arbeitsdruck-und-entwicklung",
    number: 5,
    title: "Робочий тиск і розвиток",
    promptZh:
      "真正进入工作场景后，单词会和压力、协调、成长、安排一起出现。这一组更适合做复述和情境表达训练。",
    promptEn:
      "In real work situations, vocabulary appears together with pressure, coordination, growth and planning. This set is useful for retelling and situational speaking.",
    sections: [
      {
        id: "staerken-stress-und-vorbereitung",
        tabLabel: "Стрес",
        tabLabelZh: "压力与准备",
        sectionTitle: "A. Сильні сторони та підготовка",
        sectionTitleZh: "优点、压力与准备",
        words: [
          ["виклик", "difficult but interesting task", "挑战"],
          ["слабкість", "less strong side", "弱点"],
          ["стабільність", "feeling of safety or steadiness", "安全；稳定"],
          ["сильна сторона", "special positive quality", "优点；长处"],
          ["стрес", "inner or outer burden", "压力"],
          ["список справ", "list of things that need to be done", "待办事项清单"],
          ["звільнятися з", "to stop working at a place", "在……离职"],
          ["продовжувати вчитися", "to keep learning new things", "继续学习；不断进步"],
          ["дістатися сюди", "to find the way here", "找到这里；到达这里"],
          ["бачити всю картину", "to keep an overview", "保持全局掌握"],
          ["поводитися з", "to handle something", "应对；处理"],
          ["готуватися до", "to prepare for something", "为……做准备"],
          ["доречний", "fitting and appropriate", "合适的；恰当的"],
          ["професійний", "related to work", "职业上的"],
          ["вмотивований", "driven from within", "有动力的"],
          ["поступово", "step by step", "逐渐地"],
          ["відповідальний за", "responsible for something", "负责……"]
        ]
      },
      {
        id: "ueberstunden-und-entlastung",
        tabLabel: "Навантаження",
        tabLabelZh: "工作负担",
        sectionTitle: "B. Навантаження і відгул",
        sectionTitleZh: "工作负担与调休请假",
        words: [
          ["звернення", "wish or request", "请求；需求"],
          ["робоче навантаження", "amount of work and pressure", "工作负担"],
          ["тимчасовий працівник", "person for temporary support", "临时工"],
          ["понаднормова година", "extra hour of work", "加班"],
          ["розуміння", "sympathy or insight", "理解"],
          ["відгул", "time off for extra work", "调休"],
          ["зменшувати", "to reduce something", "减少；消除"],
          ["узгоджувати з", "to agree on something together", "与……协商"],
          ["опрацьовувати", "to work on and complete", "处理"],
          ["займати", "to employ or occupy oneself with", "雇用；从事"],
          ["домовлятися про", "to come to a common solution", "就……达成一致"],
          ["отримати вихідний", "to receive time off", "获得休假"],
          ["взяти вихідний", "to take time off", "请假"],
          ["дбати про", "to take care of or handle", "照顾；处理"],
          ["працювати", "to function or proceed", "进行；运转"],
          ["брати відпустку", "to use vacation days", "休假"],
          ["власне", "in reality", "其实"],
          ["тим часом", "meanwhile / by now", "与此同时；现在"],
          ["можливо", "possibly", "也许"],
          ["справді", "really", "真的"]
        ]
      },
      {
        id: "karriere-und-weiterbildung",
        tabLabel: "Розвиток",
        tabLabelZh: "发展与学习",
        sectionTitle: "C. Кар'єра і навчання",
        sectionTitleZh: "职业发展与继续教育",
        words: [
          ["пропозиція", "proposal or commercial offer", "提供；报价"],
          ["оснащення", "technical or material equipment", "配置；设备"],
          ["галузь", "economic field", "行业"],
          ["офісна робота", "work done in an office", "办公室工作"],
          ["застосування", "concrete use or engagement", "使用；投入"],
          ["успіх", "good result", "成功"],
          ["апаратне забезпечення", "physical technical devices", "硬件"],
          ["інститут", "research or educational institution", "研究所；机构"],
          ["кар'єра", "professional path", "职业生涯"],
          ["онлайн-навчання", "teaching over the internet", "在线教学"],
          ["презентація", "structured presentation of content", "展示；演示"],
          ["очне навчання", "in-person teaching", "线下教学"],
          ["рахунок", "document with amount to pay", "账单"],
          ["програмне забезпечення", "computer programs", "软件"],
          ["тренер", "person who leads training or courses", "培训师"],
          ["робота з", "way of dealing with something", "与……的处理方式"],
          ["сертифікат", "official proof of competence", "证书"],
          ["досліджувати", "to search for information", "查资料；研究"],
          ["визнаний", "officially accepted", "被认可的"],
          ["ефективний", "with good effect", "有效的"],
          ["конкретний", "clear and exact", "具体的"],
          ["кваліфікований", "professionally suitable", "有资格的"],
          ["серйозний", "reliable and credible", "可靠的"],
          ["широкий", "comprehensive and extensive", "全面的"],
          ["ймовірно", "probably", "可能"]
        ]
      }
    ]
  },
  {
    id: "bueroalltag-und-service",
    number: 6,
    title: "Офісні процеси та сервіс",
    promptZh:
      "办公室协作和客户沟通常常是一起训练的：一边要会请假、填表、和上级协调，一边还要会推荐、解释、处理投诉。",
    promptEn:
      "Office coordination and customer-facing service are often learned together: sick leave, forms, supervisors, recommendations and complaints all belong to the same work routine.",
    sections: [
      {
        id: "bueroalltag-und-krankmeldung",
        tabLabel: "Офіс",
        tabLabelZh: "办公室流程",
        sectionTitle: "A. Офіс і лікарняний",
        sectionTitleZh: "办公室流程与请病假",
        words: [
          ["відділ", "organisational part of a company", "部门"],
          ["довідка про непрацездатність", "official proof of illness and inability to work", "病假证明"],
          ["медична довідка", "doctor's certificate", "证明（医疗）"],
          ["доручення", "specific work task or order", "任务；订单"],
          ["працівник", "person in an employment relationship", "员工"],
          ["керівництво компанії", "management of a company", "公司管理层"],
          ["внутрішня мережа", "internal digital company network", "公司内网"],
          ["анкета працівника", "form with personal employee data", "人事表"],
          ["керівник", "direct supervising person", "上级；主管"],
          ["завершувати", "to complete something as planned", "完成（课程/培训）"],
          ["узгоджуватися з", "to coordinate with someone", "与……协调"],
          ["радитися з", "to discuss something with someone", "与……商量"],
          ["виконувати", "to bring something to completion", "完成；处理"],
          ["повідомляти про хворобу", "to report being sick", "请病假"]
        ]
      },
      {
        id: "beratung-und-auswahl",
        tabLabel: "Сервіс",
        tabLabelZh: "服务沟通",
        sectionTitle: "B. Консультація та вибір",
        sectionTitleZh: "推荐、咨询与客户沟通",
        words: [
          ["вибір", "set of possible options", "选择"],
          ["планшет", "portable computer with touchscreen", "平板电脑"],
          ["пропонувати", "to offer something as an option", "提供"],
          ["порушувати тему", "to mention a topic or initiate contact", "提及；沟通"],
          ["консультувати", "to advise or inform professionally", "咨询；建议"],
          ["скаржитися до", "to express a complaint to someone", "向……投诉"],
          ["рекомендувати", "to suggest something as good", "推荐"],
          ["запитувати про", "to ask specifically about something", "询问"],
          ["висіти", "to be in a hanging position", "悬挂"],
          ["класти", "to put something down flat", "放（平放）"],
          ["лежати", "to be lying somewhere", "位于；放着"],
          ["перевіряти", "to check something briefly", "查看"],
          ["ставити", "to place something upright", "放（竖立）"],
          ["стояти", "to be standing in a place", "站立；放着"],
          ["відомий завдяки", "famous for something", "以……闻名"],
          ["індивідуальний", "adapted to a single person", "个别的"],
          ["інтенсивний", "strong and concentrated", "密集的"]
        ]
      }
    ]
  },
  {
    id: "ausbildung-technik-und-arbeitsmarkt",
    number: 7,
    title: "Навчання, техніка та ринок праці",
    promptZh:
      "这一组把职业培训、设备说明和就业市场放在同一条学习线上，适合从学习走向工作、再走向就业市场的过渡复习。",
    promptEn:
      "This topic connects vocational training, device language and labour-market vocabulary in one practical study path.",
    sections: [
      {
        id: "ausbildung-im-betrieb",
        tabLabel: "Навчання",
        tabLabelZh: "培训与车间",
        sectionTitle: "A. Навчання на підприємстві",
        sectionTitleZh: "企业培训与工作交接",
        words: [
          ["наставник", "person who trains apprentices", "培训师"],
          ["рік навчання", "one year within vocational training", "培训年"],
          ["учень-практикант", "person in vocational training", "学徒"],
          ["професійна школа", "school alongside vocational training", "职业学校"],
          ["замовлення", "purchase order", "订单"],
          ["запасна частина", "part used for replacement", "备件"],
          ["кінець робочого дня", "time after work", "下班时间"],
          ["передача", "handover to the next person", "交接"],
          ["забирати", "to pick something up", "取；接"],
          ["діставати", "to organise or procure something", "采购；办理"],
          ["встановлювати", "to install into something", "安装"],
          ["налаштовувати", "to set or adjust", "雇用"],
          ["ламатися", "to stop functioning", "坏掉"],
          ["відбуватися", "to happen", "发生；有情况"],
          ["монтувати", "to assemble parts", "组装"],
          ["вистачати", "to be enough", "足够"],
          ["ремонтувати", "to repair", "修理"],
          ["заходити", "to come by briefly", "顺便来"],
          ["напружений", "stressful", "有压力的"]
        ]
      },
      {
        id: "geraete-und-sicherheit",
        tabLabel: "Техніка",
        tabLabelZh: "设备与安全",
        sectionTitle: "B. Пристрої та безпека",
        sectionTitleZh: "设备、材料与安全提示",
        words: [
          ["інструкція з використання", "manual for using a device", "使用说明书"],
          ["пристрій", "technical device or machine", "设备"],
          ["ручка", "part used to hold something", "把手"],
          ["дерево", "material from trees", "木头"],
          ["ознака", "typical feature", "特征"],
          ["метал", "solid technical material", "金属"],
          ["пластик", "synthetic material", "塑料"],
          ["вимикач", "switch for turning on or off", "开关"],
          ["вказівка з безпеки", "important safety notice", "安全提示"],
          ["розетка", "socket for electricity", "插座"],
          ["штекер", "plug for electricity", "插头"],
          ["тканина", "material or fabric", "材料"],
          ["замовляти", "to order for delivery", "订购"],
          ["вмикати", "to switch on", "打开（电源）"],
          ["вимикати", "to switch off", "关闭（电源）"],
          ["йдеться про", "to be about something", "涉及；是关于"],
          ["гарної форми", "beautifully designed", "造型美观的"],
          ["зручний", "easy to use and carry", "便于使用的"],
          ["потужний", "high-performing", "性能强的"],
          ["міцний", "resistant and durable", "结实的"],
          ["стійкий", "stable and secure", "稳定的"]
        ]
      },
      {
        id: "neuorientierung-am-arbeitsmarkt",
        tabLabel: "Ринок праці",
        tabLabelZh: "就业市场",
        sectionTitle: "C. Переорієнтація на ринку праці",
        sectionTitleZh: "就业市场与职业转向",
        words: [
          ["служба зайнятості", "public office for job search", "就业局"],
          ["ринок праці", "job market", "劳动力市场"],
          ["сфера", "specialised area", "领域"],
          ["перекваліфікація", "professional retraining", "再培训"],
          ["працювати в", "to work in a field", "在……工作"],
          ["добре розбиратися в", "to know something well", "熟悉；精通"],
          ["дізнаватися про", "to gather information about", "了解；查询"],
          ["орієнтуватися", "to find a new direction", "重新定位方向"],
          ["змінюватися", "to become different", "改变"],
          ["альтернативний", "offering another option", "替代的"],
          ["зайнятий", "already occupied", "已被占用"],
          ["цифровий", "digital and data-based", "数字化的"],
          ["затребуваний", "in demand", "受欢迎的"],
          ["додатково до основної роботи", "alongside the main job", "兼职的"],
          ["регулярний", "at equal intervals", "定期的"],
          ["з причин здоров'я", "for health reasons", "出于健康原因"],
          ["хороші шанси на ринку праці", "good prospects for finding work", "在就业市场上有好机会"]
        ]
      }
    ]
  },
  {
    id: "unternehmen-und-empfang",
    number: 8,
    title: "Компанія та ресепшен",
    promptZh:
      "这一组围绕公司介绍、前台接待和跨部门沟通，适合把企业结构词和真实办公动作连起来学。",
    promptEn:
      "This topic focuses on company profiles, reception work and internal coordination.",
    sections: [
      {
        id: "firmenprofil-und-empfang",
        tabLabel: "Компанія",
        tabLabelZh: "公司与前台",
        sectionTitle: "A. Профіль компанії та ресепшен",
        sectionTitleZh: "公司介绍与前台接待",
        words: [
          ["властивість", "feature or characteristic quality", "特征；品质"],
          ["ставлення", "attitude", "态度；设置"],
          ["ресепшен", "reception area", "接待；前台"],
          ["гнучкість", "ability to adapt well", "灵活性"],
          ["фірма", "company", "公司"],
          ["товариство з обмеженою відповідальністю", "limited liability company", "有限责任公司"],
          ["головний офіс", "main seat of a company", "总部"],
          ["інформаційні технології", "IT field", "信息技术"],
          ["знання", "knowledge or familiarity", "知识；了解"],
          ["співробітник", "employee", "员工"],
          ["організаторський талант", "special ability to organise", "组织能力"],
          ["телефонна система", "technical phone system", "电话系统"],
          ["тренування", "practical training", "培训"],
          ["правила поведінки", "social norms of polite behaviour", "礼仪；行为规范"],
          ["умова", "required condition", "条件"],
          ["центральний офіс", "central office", "总部"],
          ["обслуговувати", "to operate or serve customers", "操作；服务"],
          ["розташовуватися", "to be situated", "位于"],
          ["вітати", "to welcome someone", "欢迎；问候"],
          ["засновувати", "to found a company", "创立"],
          ["покращувати", "to make better", "改善"],
          ["терплячий", "patient", "有耐心的"],
          ["охайний", "neat and well-groomed", "整洁的"],
          ["чуйний", "helpful", "乐于助人的"],
          ["міжнародний", "international", "国际的"],
          ["активний у сфері", "active in work", "从事工作的"],
          ["по всьому світу", "worldwide", "全球的"],
          ["акціонерне товариство", "joint-stock company", "股份公司"],
          ["дочірня компанія", "subsidiary company", "子公司"]
        ]
      },
      {
        id: "koordination-und-kommunikation",
        tabLabel: "Комунікація",
        tabLabelZh: "协调沟通",
        sectionTitle: "B. Координація та комунікація",
        sectionTitleZh: "协调、转达与商务沟通",
        words: [
          ["позначати", "to mark clearly", "标记；标识"],
          ["організовувати", "to plan and structure", "组织"],
          ["перевіряти", "to check carefully", "检查"],
          ["вести переговори з", "to negotiate with someone", "与……谈判"],
          ["пересилати", "to forward information", "转发"],
          ["співпрацювати з", "to work together with", "与……合作"],
          ["бездоганний", "without errors", "无缺陷的；完美的"],
          ["відповідальний за", "responsible for", "负责……"],
          ["уповноважений на", "officially in charge of", "负责……"],
          ["комерційний", "related to business", "商业的；经济的"],
          ["серед іншого", "among other things", "其中包括"]
        ]
      },
      {
        id: "anreise-und-besprechung",
        tabLabel: "Поїздка",
        tabLabelZh: "出差与会面",
        sectionTitle: "C. Приїзд і зустріч",
        sectionTitleZh: "出差、抵达与客户会面",
        words: [
          ["прибуття", "journey to a destination", "到达；抵达"],
          ["зустріч", "meeting for work exchange", "会议"],
          ["рейс", "flight", "航班"],
          ["дорога додому", "journey back home", "返程"],
          ["новий клієнт", "newly acquired customer", "新客户"],
          ["приїжджати", "to arrive", "到达；抵达"],
          ["дати знати", "to inform someone", "告知"],
          ["прибувати", "to arrive at a place", "到达"],
          ["інформувати", "to notify", "通知；告知"],
          ["проходити", "to develop in a certain way", "进行；进展"],
          ["потенційний", "possible or potential", "潜在的"],
          ["безперебійний", "smooth and without problems", "顺利的"]
        ]
      }
    ]
  },
  {
    id: "duales-studium-und-berufsstart",
    number: 9,
    title: "Дуальна освіта та початок кар'єри",
    promptZh:
      "双元制、实践学习和正式进入职场常常是一条连续的成长路径，这一组适合把理论、实践和财务岗位词汇一起整理。",
    promptEn:
      "This topic links dual study, practical phases and the first steps into working life.",
    sections: [
      {
        id: "theorie-und-praxis",
        tabLabel: "Теорія і практика",
        tabLabelZh: "理论与实践",
        sectionTitle: "A. Теорія і практика",
        sectionTitleZh: "理论与实践交替",
        words: [
          ["практика", "practical application in real life", "实践"],
          ["студент", "person studying at a university", "大学生"],
          ["теорія", "scientific or conceptual knowledge", "理论"],
          ["перевага", "positive side or benefit", "优点；优势"],
          ["чергуватися", "to alternate", "轮流；交替"],
          ["створювати", "to create deliberately", "制作；创建"],
          ["виходити на пенсію", "to end working life", "退休"],
          ["рахувати", "to calculate", "计算"],
          ["академічний", "related to higher education", "学术的"],
          ["спільний", "together with others", "共同的"]
        ]
      },
      {
        id: "finanzen-und-qualifikation",
        tabLabel: "Фінанси",
        tabLabelZh: "财务与资历",
        sectionTitle: "B. Фінанси та кваліфікація",
        sectionTitleZh: "财务岗位与专业资历",
        words: [
          ["робоча сила", "human ability to work", "劳动力"],
          ["професійна академія", "college with strong practical orientation", "职业学院"],
          ["економіст підприємства", "specialist in business administration", "企业管理人员"],
          ["бухгалтерія", "area for financial records", "会计"],
          ["фінансовий бухгалтер", "specialist in financial accounting", "财务会计"],
          ["концерн", "large company group", "集团公司"],
          ["місячне / річне закриття", "monthly or yearly financial closing", "月度/年度结算"],
          ["недолік", "negative side", "缺点"],
          ["етап", "phase in a process", "阶段"]
        ]
      },
      {
        id: "arbeitsleben-und-einstieg",
        tabLabel: "Старт у професії",
        tabLabelZh: "职业起步",
        sectionTitle: "C. Трудове життя і старт",
        sectionTitleZh: "职业生活与进入职场",
        words: [
          ["трудове життя", "overall professional life phase", "职业生活"],
          ["професія за навчанням", "occupation learned during training", "培训职业"],
          ["учень", "person in vocational training", "学徒"],
          ["азубі", "informal word for apprentice", "学徒（口语）"],
          ["вхід у професію", "beginning of working life", "进入职场"],
          ["професійна школа", "school parallel to training", "职业学校"],
          ["шкільний атестат", "official school leaving certificate", "毕业证书"],
          ["надавати", "to deliver or provide", "提供；完成"],
          ["дуальний", "based on two learning places", "双元制的"]
        ]
      }
    ]
  },
  {
    id: "arbeitsalltag-und-regelungen",
    number: 10,
    title: "Робочі будні та правила",
    promptZh:
      "真正入职之后，最常见的是和工作流程、办公室规则、请假、观察、沟通有关的表达，这一组适合做情境复盘。",
    promptEn:
      "After starting a real job, vocabulary about routines, office rules, leave and communication becomes especially important.",
    sections: [
      {
        id: "erster-arbeitstag",
        tabLabel: "Перший день",
        tabLabelZh: "第一天与印象",
        sectionTitle: "A. Перший робочий день",
        sectionTitleZh: "工作日、印象与适应",
        words: [
          ["робоча атмосфера", "team atmosphere at work", "工作氛围"],
          ["робочий день", "day with professional tasks", "工作日"],
          ["офісна будівля", "building with offices", "办公楼"],
          ["враження", "effect something makes on a person", "印象"],
          ["людина", "a person", "人"],
          ["екскурсія", "short guided tour", "参观；巡视"],
          ["тиск часу", "pressure because time is short", "时间压力"],
          ["розпочинати роботу", "to take up a job", "入职"],
          ["справити враження", "to leave an impression", "留下印象"],
          ["у", "at a place or with a person", "在……（某人处）"],
          ["одягнений", "dressed in a certain way", "穿着……的"],
          ["до подальшого повідомлення", "until further notice", "暂时；直到另行通知"]
        ]
      },
      {
        id: "pflichten-und-unterlagen",
        tabLabel: "Правила",
        tabLabelZh: "规则与文件",
        sectionTitle: "B. Обов'язки та документи",
        sectionTitleZh: "规则、权利与必备文件",
        words: [
          ["обідня перерва", "pause at midday", "午休"],
          ["мотивація", "inner drive", "动力"],
          ["правило перерв", "regulation concerning breaks", "休息规定"],
          ["обов'язок", "something one must do", "义务"],
          ["порада", "well-meant advice", "建议"],
          ["право", "legitimate right", "权利"],
          ["регулювання", "specific rule", "规定"],
          ["посвідчення соціального страхування", "official social insurance document", "社保证明"],
          ["правило гри", "agreed rule of interaction", "规则"],
          ["податковий ідентифікаційний номер", "official personal tax number", "税号"],
          ["тарифний договір", "collective labour agreement", "集体合同"],
          ["надурочна година", "extra working hour", "加班"],
          ["документи", "documents or materials", "材料；文件"],
          ["адміністрація", "administrative department", "行政管理"],
          ["керівник", "person with managerial responsibility", "上级；主管"]
        ]
      },
      {
        id: "verhalten-und-ablauf",
        tabLabel: "Поведінка",
        tabLabelZh: "行为与流程",
        sectionTitle: "C. Поведінка і процес",
        sectionTitleZh: "行为规范与工作流程",
        words: [
          ["залежати від", "to depend on", "取决于"],
          ["пристосовуватися до", "to adapt to", "适应"],
          ["відповідати", "to answer", "回答"],
          ["спостерігати", "to observe carefully", "观察"],
          ["враховувати", "to take into account", "考虑到"],
          ["існувати", "to exist", "存在；成立"],
          ["очікувати", "to expect", "期待"],
          ["давати пораду", "to give advice", "提出建议"],
          ["схвалювати", "to approve officially", "批准"],
          ["дотримуватися", "to follow a rule", "遵守"],
          ["тримати очі й вуха відкритими", "to stay alert", "保持警觉"],
          ["перепитувати щодо", "to ask again about", "询问"],
          ["врегульовувати", "to regulate or handle", "规定；处理"],
          ["поводитися з", "to handle", "应对"],
          ["йти назустріч", "to approach actively", "接近；走向"],
          ["зацікавлений", "interested", "感兴趣的"],
          ["об'єктивний", "factual and objective", "客观的"],
          ["обов'язковий", "binding and reliable", "有约束力的；可靠的"],
          ["процес", "order or sequence", "流程"],
          ["вказівка", "clear instruction", "指示"],
          ["необхідне", "what is necessary", "必要的事情"],
          ["правило", "general rule", "规则"],
          ["обговорювати", "to discuss together", "讨论"],
          ["підтримувати", "to support", "支持"],
          ["завчасно", "early enough", "提前地"],
          ["часовий", "related to time", "时间上的"]
        ]
      }
    ]
  },
  {
    id: "bewerbung-und-lebenslauf-vertiefung",
    number: 11,
    title: "Поглиблено: заявка та резюме",
    promptZh:
      "这一组把简历信息、书面表达、招聘广告和零售岗位要求连成一条完整的求职线，更适合进阶复习。",
    promptEn:
      "This topic deepens CV, written-application and job-ad vocabulary into one complete application path.",
    sections: [
      {
        id: "lebenslauf-und-daten",
        tabLabel: "Резюме",
        tabLabelZh: "简历信息",
        sectionTitle: "A. Резюме та дані",
        sectionTitleZh: "简历、信息与个人资料",
        words: [
          ["резюме", "CV overview of education and work", "简历"],
          ["дані", "information or data", "数据；信息"],
          ["дата народження", "day of birth", "出生日期"],
          ["місце народження", "place of birth", "出生地"],
          ["громадянство", "legal nationality", "国籍"],
          ["шкільна освіта", "school education history", "学历"],
          ["професійна підготовка", "vocational qualification", "培训"],
          ["диплом", "official completion certificate", "毕业证书"],
          ["досвід роботи", "experience from previous work", "工作经验"],
          ["мовні знання", "knowledge of languages", "语言能力"],
          ["рідна мова", "first language", "母语"],
          ["підвищення кваліфікації", "further professional training", "进修"],
          ["звіт про продажі", "sales statement", "销售结算"],
          ["освітній центр", "centre for learning and courses", "教育中心"],
          ["товарознавство", "knowledge about goods", "商品知识"],
          ["кваліфікаційна підготовка", "qualification or certification", "资格认证"],
          ["відділ кадрів", "HR office", "人事办公室"],
          ["супровідний лист", "written application text", "求职信"],
          ["телефонна розмова", "conversation by phone", "电话通话"],
          ["знайомий", "person one knows", "熟人"],
          ["співбесіда", "job interview", "面试"],
          ["довідка", "official certificate", "证明"],
          ["дискаунтер", "discount store", "折扣店"],
          ["папка для заявки", "folder with application documents", "求职资料夹"]
        ]
      },
      {
        id: "anschreiben-und-formulierung",
        tabLabel: "Формулювання",
        tabLabelZh: "书写表达",
        sectionTitle: "B. Формулювання та лист",
        sectionTitleZh: "求职表达与书写质量",
        words: [
          ["подаватися", "to apply", "申请"],
          ["досліджувати", "to research", "查资料"],
          ["особистий", "personal", "个人的"],
          ["усний", "spoken", "口头的"],
          ["письмовий", "written", "书面的"],
          ["спеціальний", "specific", "特别的"],
          ["професійний", "related to profession", "职业的"],
          ["випускна оцінка", "final grade", "毕业成绩"],
          ["вимога", "specific requirement", "要求"],
          ["професійна освіта", "vocational education", "职业培训"],
          ["фото для заявки", "application photo", "证件照"],
          ["розмова щодо заявки", "interview in application process", "面试"],
          ["базові знання", "basic knowledge", "基础知识"],
          ["оцінка", "grade", "成绩"],
          ["кадровик", "HR person", "人事人员"],
          ["особисті дані", "personal details", "个人信息"],
          ["правопис", "correct spelling", "拼写"],
          ["правильність", "correctness", "正确性"],
          ["ймовірність", "probability", "可能性"],
          ["пристосовувати до", "to adapt to", "适应"],
          ["володіти", "to master", "掌握"],
          ["оснащувати", "to equip with", "配有"],
          ["складати текст", "to compose a text", "撰写"],
          ["офіційний", "formal and official", "正式的"],
          ["наочний", "clearly structured", "清晰的"],
          ["серйозний", "reliable and credible", "严肃的；可靠的"],
          ["несерйозний", "not trustworthy", "不可靠的"],
          ["професійний", "professional", "专业的"],
          ["власноручний", "done personally by hand", "亲自的"]
        ]
      },
      {
        id: "stellenanzeige-und-handel",
        tabLabel: "Оголошення",
        tabLabelZh: "招聘与零售",
        sectionTitle: "C. Оголошення та торгівля",
        sectionTitleZh: "招聘广告与零售岗位",
        words: [
          ["оголошення про вакансію", "public ad for an open job", "招聘广告"],
          ["магазин делікатесів", "shop for fine foods", "食品专卖店"],
          ["роздрібна торгівля", "retail trade", "零售业"],
          ["консультація", "professional advice", "咨询"],
          ["відразу", "from now on", "立即"],
          ["в ідеалі", "ideally", "理想情况下"],
          ["додаток", "attached document", "附件"],
          ["тема", "subject of a letter", "主题"],
          ["прийняття", "acceptance or hiring", "录用；接受"],
          ["сильна сторона", "special positive ability", "优点"],
          ["випробувальний термін", "trial period", "试用期"],
          ["заповнювати", "to fill in", "填写"],
          ["необхідний", "required", "必要的"],
          ["після цього", "afterwards", "随后"],
          ["уподобання", "personal preference", "偏好"],
          ["здібність", "ability", "能力"],
          ["товар", "product for sale", "商品"],
          ["кваліфікація", "professional suitability", "资格"],
          ["досвід", "experience", "经验"],
          ["уміння працювати в команді", "team ability", "团队能力"],
          ["продавець роздрібної торгівлі", "male retail specialist", "零售商人"],
          ["продавчиня роздрібної торгівлі", "female retail specialist", "女零售商人"],
          ["керівник", "male leader", "负责人"],
          ["керівниця", "female leader", "女负责人"],
          ["відділ продуктів", "food department", "食品部门"],
          ["універмаг", "department store", "百货公司"],
          ["відпустка по догляду за дитиною", "parental leave", "育儿假"],
          ["мережа", "chain of stores", "连锁店"],
          ["помічник", "assistant worker", "助手"],
          ["шанс", "good opportunity", "机会"],
          ["адресувати", "to direct to someone", "寄给；面向"],
          ["компетентний", "expert", "专业的"],
          ["успішний", "successful", "成功的"],
          ["звичний", "common", "常见的"],
          ["цілковитий", "complete", "完全的"],
          ["гнучкий", "flexible", "灵活的"],
          ["надмірно кваліфікований", "overqualified", "资历过高的"],
          ["придатний для", "suitable for", "适合"]
        ]
      }
    ]
  },
  {
    id: "unternehmen-und-abteilungen",
    number: 12,
    title: "Компанія та відділи",
    promptZh:
      "介绍一家公司时，很快就会进入部门、采购、生产、研发、市场和供应商这些结构化词汇，这一组最适合按组织图来记。",
    promptEn:
      "When describing a company, structured vocabulary about departments, purchasing, production and marketing becomes essential.",
    sections: [
      {
        id: "struktur-und-abteilungen",
        tabLabel: "Структура",
        tabLabelZh: "组织结构",
        sectionTitle: "A. Структура та відділи",
        sectionTitleZh: "组织结构与部门名称",
        words: [
          ["відділ", "organisational part of a company", "部门"],
          ["робочий клімат", "atmosphere in the company", "工作氛围"],
          ["закупівлі", "department responsible for procurement", "采购"],
          ["розробка", "development or R&D area", "发展；研发"],
          ["фінанси", "area for money and budgets", "财务"],
          ["керівництво", "top management", "管理层"],
          ["виробництво", "making products", "生产"],
          ["маркетинг", "market and advertising area", "市场营销"],
          ["органіграмa", "graphic company structure chart", "组织结构图"],
          ["персонал", "staff of a company", "员工；人事"],
          ["відділ кадрів", "HR department", "人事部门"],
          ["продукція", "production area", "生产"],
          ["сировина", "raw material", "原材料"],
          ["структура", "internal structure", "结构"],
          ["підприємство", "company or enterprise", "公司；企业"],
          ["збут", "sales distribution area", "销售"],
          ["рекламна кампанія", "planned advertising action", "广告活动"],
          ["постачальник", "supplier firm", "供应商"]
        ]
      },
      {
        id: "prozesse-und-aufbau",
        tabLabel: "Процеси",
        tabLabelZh: "流程与建设",
        sectionTitle: "B. Процеси та розвиток",
        sectionTitleZh: "流程、建设与发展动作",
        words: [
          ["звертати увагу на", "to pay attention to", "注意"],
          ["будувати", "to build up gradually", "建立"],
          ["потребувати", "to need", "需要"],
          ["займатися", "to deal with something", "从事；研究"],
          ["наймати", "to employ", "雇用"],
          ["розвивати", "to develop", "发展；开发"]
        ]
      }
    ]
  }
];
