window.IMPORTED_GERMAN_TOPICS = [
  {
    id: "arbeitsmodelle-und-stellenmarkt",
    number: 3,
    title: "Arbeitsmodelle und Stellenmarkt",
    promptZh:
      "这一组是德语里最常用的求职和工作框架词。先把工作形式、岗位条件和招聘关键词分开记，再用职位广告的语境把它们串起来，记忆会更牢。",
    promptEn:
      "This topic groups together the framework vocabulary of work: job types, contract conditions and common terms from job ads. If you separate these patterns first and then reuse them in job-posting contexts, recall becomes much easier.",
    sections: [
      {
        id: "arbeitsformen-und-zeiten",
        tabLabel: "Arbeitsformen",
        tabLabelZh: "工作形式",
        sectionTitle: "A. Arbeitsformen und Zeiten",
        sectionTitleZh: "工作形式与时间安排",
        words: [
          ["die Ausbildung", "berufliche Qualifizierung für einen Beruf", "职业培训"],
          ["die Elternzeit", "Zeit nach der Geburt eines Kindes", "育儿假"],
          ["der Minijob", "kleine Arbeit mit geringem Einkommen", "低收入兼职"],
          ["das Praktikum", "praktische Tätigkeit zum Lernen", "实习"],
          ["die Sprachkenntnisse", "Fähigkeit, eine Sprache zu benutzen", "语言能力"],
          ["die Stelle", "angebotene Arbeitsposition", "职位"],
          ["die Teilzeit", "Arbeit mit reduzierten Stunden", "兼职"],
          ["die Vollzeit", "Arbeit mit voller Wochenarbeitszeit", "全职"],
          ["arbeitslos", "ohne Arbeit oder Beschäftigung", "失业的"],
          ["befristet", "nur für eine bestimmte Zeit gültig", "有期限的"],
          ["unbefristet", "ohne festes Enddatum", "无固定期限的"],
          ["im Moment", "zurzeit oder aktuell", "目前"],
          ["Stunden pro Woche", "Zahl der Arbeitsstunden in einer Woche", "每周小时数"]
        ]
      },
      {
        id: "betrieb-und-bedingungen",
        tabLabel: "Bedingungen",
        tabLabelZh: "工作条件",
        sectionTitle: "B. Betrieb und Bedingungen",
        sectionTitleZh: "企业、条件与招聘用语",
        words: [
          ["das Arbeitsklima", "Atmosphäre am Arbeitsplatz", "工作氛围"],
          ["die Arbeitszeit", "Zeit, in der man arbeitet", "工作时间"],
          ["die Berufsausbildung", "Ausbildung für einen bestimmten Beruf", "职业培训"],
          ["die Berufserfahrung", "praktische Erfahrung im Beruf", "工作经验"],
          ["der Betrieb", "Unternehmen oder Firma", "企业"],
          ["die Bewerbung", "Unterlagen für eine Stelle", "求职申请"],
          ["die Bewerbungsunterlagen", "alle Dokumente für eine Bewerbung", "申请材料"],
          ["die Bezahlung", "Lohn oder Gehalt für eine Arbeit", "薪资"],
          ["der Kunde", "Person oder Firma, die etwas kauft", "客户"],
          ["der Mitarbeiter", "Person, die in einer Firma arbeitet", "员工"],
          ["der Stundenlohn", "Lohn pro Arbeitsstunde", "时薪"],
          ["das Team", "Gruppe, die zusammen arbeitet", "团队"],
          ["die Vertretung", "Person, die jemanden ersetzt", "替代；代理"],
          ["die Voraussetzung", "Bedingung, die erfüllt sein muss", "条件"],
          ["die Weiterbildung", "berufliches Lernen nach der Ausbildung", "进修；继续教育"],
          ["die Zeitarbeitsfirma", "Firma für befristete Einsätze", "劳务派遣公司"],
          ["sich bewerben", "eine Bewerbung schicken", "申请（工作）"],
          ["bieten", "zur Verfügung stellen", "提供"],
          ["abgeschlossen", "erfolgreich beendet", "完成的"],
          ["beschäftigt", "in Arbeit oder angestellt", "在职的"],
          ["modern", "neu und zeitgemäß", "现代的"],
          ["nachhaltig", "auf Dauer sinnvoll und umweltbewusst", "可持续的"],
          ["ökologisch", "die Umwelt berücksichtigend", "生态的"],
          ["selbständig", "eigenverantwortlich oder freiberuflich", "自主的；个体经营的"],
          ["vollständig", "ohne fehlende Teile", "完整的"],
          ["wünschenswert", "besonders erwünscht", "理想的；可取的"],
          ["m/w/d", "Abkürzung für männlich, weiblich und divers", "职位标注：男性 / 女性 / 多元", "常见职位标注：m = männlich，w = weiblich，d = divers。"],
          ["ab sofort", "direkt von jetzt an", "立即；从现在开始"]
        ]
      },
      {
        id: "fachkraft-und-stellenprofil",
        tabLabel: "Stellenprofil",
        tabLabelZh: "岗位画像",
        sectionTitle: "C. Fachkraft und Stellenprofil",
        sectionTitleZh: "岗位画像与招聘偏好",
        words: [
          ["die Fachkraft", "qualifizierte Person im Beruf", "专业人员"],
          ["der Nebenjob", "zusätzliche Arbeit neben dem Hauptberuf", "兼职"],
          ["die Qualifikation", "fachliche Voraussetzung für eine Arbeit", "资格；资历"],
          ["der Raum", "Gebiet oder Region", "地区"],
          ["die Verhandlungsbasis", "Ausgangspunkt für Verhandlungen", "谈判基础"],
          ["das Wunschbruttogehalt", "gewünschtes Gehalt vor Steuern", "期望税前工资"],
          ["die Zuschrift", "schriftliche Nachricht oder Bewerbung", "来信；申请信"],
          ["kontaktieren", "mit jemandem Kontakt aufnehmen", "联系"],
          ["übernehmen", "eine Aufgabe an sich nehmen", "承担；接手"],
          ["bevorzugt", "lieber oder mit Vorrang", "优先的"],
          ["engagiert", "aktiv und motiviert", "积极投入的"],
          ["flexibel", "leicht an neue Situationen anpassbar", "灵活的"],
          ["fundiert", "inhaltlich gut begründet", "扎实的"],
          ["günstig", "vorteilhaft oder preiswert", "有利的；便宜的"],
          ["langjährig", "über viele Jahre bestehend", "多年的"],
          ["professionell", "fachlich und korrekt", "专业的"],
          ["sorgfältig", "genau und aufmerksam", "仔细的"],
          ["teamorientiert", "auf Zusammenarbeit im Team ausgerichtet", "有团队精神的"],
          ["vorhanden", "da oder verfügbar", "现有的"],
          ["zuverlässig", "so, dass man sich darauf verlassen kann", "可靠的"],
          ["möglichst", "so gut wie möglich", "尽可能"]
        ]
      }
    ]
  },
  {
    id: "anerkennung-und-bewerbung",
    number: 4,
    title: "Anerkennung und Bewerbung",
    promptZh:
      "这里把“资格认证”和“求职表达”放在一起，是因为很多真实场景里它们会连着出现：先证明资格，再写申请、进面试、谈入职条件。",
    promptEn:
      "Recognition of qualifications and job application language often appear together in real life: first you prove your qualification, then you write the application, attend the interview and talk about starting conditions.",
    sections: [
      {
        id: "anerkennung-und-nachweise",
        tabLabel: "Anerkennung",
        tabLabelZh: "资格认证",
        sectionTitle: "A. Anerkennung und Nachweise",
        sectionTitleZh: "资格认证与证明材料",
        words: [
          ["die Anerkennung", "offizielle Bestätigung oder Akzeptanz", "认可"],
          ["die Berufsanerkennung", "offizielle Anerkennung eines Berufsabschlusses", "职业资格认证"],
          ["der Antrag", "formelle Bitte bei einer Stelle", "申请"],
          ["die Beratungsstelle", "Ort für Beratung und Hilfe", "咨询机构"],
          ["der Berufsabschluss", "offizieller Abschluss für einen Beruf", "职业资格证书"],
          ["die Dauer", "Länge einer Zeitspanne", "时长"],
          ["das Formular", "schriftliches Eingabedokument", "表格"],
          ["das Gehalt", "fester Lohn pro Monat", "工资"],
          ["die Nachtschicht", "Arbeit in der Nacht", "夜班"],
          ["der Nachweis", "offizieller Beleg oder Beweis", "证明"],
          ["die Pflegekraft", "Person in einem Pflegeberuf", "护理人员"],
          ["die Prüfung", "offizieller Test", "考试"],
          ["die Übersetzung", "Übertragung in eine andere Sprache", "翻译"],
          ["das Zeugnis", "offizielles Dokument über Leistung oder Abschluss", "证书"],
          ["anerkennen", "offiziell akzeptieren", "承认；认可"],
          ["anstellen", "jemanden in Arbeit nehmen", "雇用"],
          ["helfen", "Unterstützung geben", "帮助"],
          ["schaffen", "etwas erfolgreich bewältigen", "完成；做到"],
          ["verdienen", "Geld durch Arbeit bekommen", "赚取"],
          ["hilfsbereit", "bereit zu helfen", "乐于助人的"],
          ["höflich", "freundlich und respektvoll", "礼貌的"],
          ["kompetent", "fachlich sicher und fähig", "有能力的；专业的"]
        ]
      },
      {
        id: "anschreiben-und-interview",
        tabLabel: "Bewerbung",
        tabLabelZh: "求职沟通",
        sectionTitle: "B. Anschreiben und Interview",
        sectionTitleZh: "求职信、面试与表达",
        words: [
          ["das Bewerbungsschreiben", "schriftlicher Text für eine Bewerbung", "求职信"],
          ["die Einladung", "Bitte, zu einem Termin zu kommen", "邀请"],
          ["der Eintrittstermin", "Zeitpunkt des Arbeitsbeginns", "入职时间"],
          ["die Erfahrung", "Wissen aus praktischem Erleben", "经验"],
          ["die Flexibilität", "Fähigkeit, sich gut anzupassen", "灵活性"],
          ["das Interesse", "innere Bereitschaft oder Neugier", "兴趣"],
          ["die Kompetenz", "fachliche Fähigkeit", "能力"],
          ["die Soft Skills", "persönliche und soziale Fähigkeiten", "软技能"],
          ["die Teamfähigkeit", "Fähigkeit zur Zusammenarbeit", "团队合作能力"],
          ["das Vorstellungsgespräch", "Gespräch für eine Bewerbung", "面试"],
          ["die Zuverlässigkeit", "Eigenschaft, verlässlich zu sein", "可靠性"],
          ["achten auf", "bewusst beachten", "注意"],
          ["anfangen bei", "bei etwas oder jemandem beginnen", "从……开始"],
          ["sich bewerben um", "sich für eine Stelle melden", "申请（职位）"],
          ["bitten um", "höflich um etwas fragen", "请求"],
          ["Erfahrungen sammeln", "praktische Erfahrung gewinnen", "积累经验"],
          ["sich freuen über", "wegen etwas froh sein", "对……感到高兴"],
          ["einen Kurs besuchen", "an einem Kurs teilnehmen", "参加课程"],
          ["passen zu", "gut zu etwas passen", "适合"],
          ["tätig sein als", "in einem Beruf arbeiten als", "从事……工作"],
          ["zur Verfügung stehen", "verfügbar sein", "可供使用；有空"],
          ["zusammenarbeiten mit", "gemeinsam arbeiten mit", "与……合作"],
          ["ausgeschrieben", "offiziell veröffentlicht", "已发布的（职位）"],
          ["erfolgreich", "mit gutem Ergebnis", "成功的"],
          ["erforderlich", "notwendig", "必要的"],
          ["frühestmöglich", "so früh wie möglich", "尽早"],
          ["selbstständig", "eigenständig arbeitend", "独立的"],
          ["teamfähig", "gut im Team arbeitend", "有团队合作能力的"],
          ["zeitlich flexibel", "bei den Zeiten anpassungsfähig", "时间灵活的"]
        ]
      }
    ]
  },
  {
    id: "arbeitsdruck-und-entwicklung",
    number: 5,
    title: "Arbeitsdruck und Entwicklung",
    promptZh:
      "真正进入工作场景后，单词不再只是名词表，而是会和‘压力、协调、成长、安排’一起出现。这一组更适合做复述和情境表达训练。",
    promptEn:
      "Once you move into real work situations, vocabulary no longer appears as isolated nouns. It comes together with pressure, coordination, growth and scheduling. This set is especially useful for retelling and situational speaking practice.",
    sections: [
      {
        id: "staerken-stress-und-vorbereitung",
        tabLabel: "Stress",
        tabLabelZh: "压力与准备",
        sectionTitle: "A. Stärken, Stress und Vorbereitung",
        sectionTitleZh: "优点、压力与准备",
        words: [
          ["die Herausforderung", "schwierige, aber interessante Aufgabe", "挑战"],
          ["die Schwäche", "weniger starke Seite", "弱点"],
          ["die Sicherheit", "Gefühl von Schutz oder Stabilität", "安全；稳定"],
          ["die Stärke", "besondere positive Eigenschaft", "优点；长处"],
          ["der Stress", "innere oder äußere Belastung", "压力"],
          ["die To-do-Liste", "Liste mit zu erledigenden Aufgaben", "待办事项清单"],
          ["aufhören bei", "eine Arbeit bei jemandem beenden", "在……离职"],
          ["dazulernen", "weiter Neues lernen", "继续学习；不断进步"],
          ["herfinden", "den Weg hierher finden", "找到这里；到达这里"],
          ["den Überblick behalten", "alles weiter gut im Blick haben", "保持全局掌握"],
          ["umgehen mit", "etwas handhaben", "应对；处理"],
          ["sich vorbereiten auf", "sich für etwas fit machen", "为……做准备"],
          ["angemessen", "passend und richtig", "合适的；恰当的"],
          ["beruflich", "die Arbeit betreffend", "职业上的"],
          ["motiviert", "mit innerem Antrieb", "有动力的"],
          ["nach und nach", "Schritt für Schritt", "逐渐地"],
          ["zuständig für", "verantwortlich für", "负责……"]
        ]
      },
      {
        id: "ueberstunden-und-entlastung",
        tabLabel: "Belastung",
        tabLabelZh: "工作负担",
        sectionTitle: "B. Überstunden und Entlastung",
        sectionTitleZh: "工作负担与调休请假",
        words: [
          ["das Anliegen", "Wunsch oder Bitte", "请求；需求"],
          ["die Arbeitsbelastung", "Menge der Arbeit und des Drucks", "工作负担"],
          ["die Aushilfskraft", "Person zur vorübergehenden Unterstützung", "临时工"],
          ["die Überstunde", "zusätzliche Arbeitsstunde", "加班"],
          ["das Verständnis", "Mitgefühl oder Einsicht", "理解"],
          ["der Zeitausgleich", "Freizeitausgleich für Mehrarbeit", "调休"],
          ["abbauen", "verringern oder reduzieren", "减少；消除"],
          ["absprechen mit", "gemeinsam vereinbaren mit", "与……协商"],
          ["bearbeiten", "an etwas arbeiten und erledigen", "处理"],
          ["beschäftigen", "Arbeit geben oder sich mit etwas befassen", "雇用；从事"],
          ["sich einigen auf", "zu einer gemeinsamen Lösung kommen", "就……达成一致"],
          ["freibekommen", "frei erhalten", "获得休假"],
          ["sich freinehmen", "sich freie Zeit nehmen", "请假"],
          ["sich kümmern um", "sich um etwas sorgen oder es erledigen", "照顾；处理"],
          ["laufen", "funktionieren oder ablaufen", "进行；运转"],
          ["Urlaub nehmen", "freie Tage benutzen", "休假"],
          ["eigentlich", "in Wirklichkeit", "其实"],
          ["mittlerweile", "inzwischen", "与此同时；现在"],
          ["vielleicht", "möglicherweise", "也许"],
          ["wirklich", "tatsächlich", "真的"]
        ]
      },
      {
        id: "karriere-und-weiterbildung",
        tabLabel: "Karriere",
        tabLabelZh: "发展与学习",
        sectionTitle: "C. Karriere und Weiterbildung",
        sectionTitleZh: "职业发展与继续教育",
        words: [
          ["das Angebot", "Vorschlag oder kommerzielle Offerte", "提供；报价"],
          ["die Ausstattung", "technische oder materielle Ausrüstung", "配置；设备"],
          ["die Branche", "wirtschaftlicher Bereich", "行业"],
          ["die Büroarbeit", "Arbeit im Büro", "办公室工作"],
          ["der Einsatz", "konkrete Verwendung oder Engagement", "使用；投入"],
          ["der Erfolg", "gutes Ergebnis", "成功"],
          ["die Hardware", "physische technische Geräte", "硬件"],
          ["das Institut", "Forschungs- oder Bildungseinrichtung", "研究所；机构"],
          ["die Karriere", "beruflicher Weg", "职业生涯"],
          ["der Online-Unterricht", "Unterricht über das Internet", "在线教学"],
          ["die Präsentation", "strukturierte Vorstellung von Inhalten", "展示；演示"],
          ["der Präsenzunterricht", "Unterricht vor Ort", "线下教学"],
          ["die Rechnung", "Dokument mit zu zahlendem Betrag", "账单"],
          ["die Software", "Programme auf dem Computer", "软件"],
          ["der/die Trainer/in", "Person, die Training oder Kurse leitet", "培训师"],
          ["der Umgang mit", "Art, mit etwas umzugehen", "与……的处理方式"],
          ["das Zertifikat", "offizieller Nachweis über Kompetenz", "证书"],
          ["recherchieren", "gezielt Informationen suchen", "查资料；研究"],
          ["anerkannt", "offiziell akzeptiert", "被认可的"],
          ["effektiv", "mit guter Wirkung", "有效的"],
          ["konkret", "klar und genau", "具体的"],
          ["qualifiziert", "fachlich geeignet", "有资格的"],
          ["seriös", "verlässlich und glaubwürdig", "可靠的"],
          ["umfangreich", "sehr umfassend", "全面的"],
          ["vermutlich", "wahrscheinlich", "可能"]
        ]
      }
    ]
  },
  {
    id: "bueroalltag-und-service",
    number: 6,
    title: "Büroalltag und Service",
    promptZh:
      "办公室协作和客户沟通常常是一起训练的：一边要会请假、填表、和上级协调，一边还要会推荐、解释、处理投诉。这组词特别适合做工作场景复盘。",
    promptEn:
      "Office coordination and customer-facing communication are often trained together: you need language for sick leave, forms and coordination with supervisors, but also for recommending, explaining and handling complaints. These words are ideal for work-situation review.",
    sections: [
      {
        id: "bueroalltag-und-krankmeldung",
        tabLabel: "Büroalltag",
        tabLabelZh: "办公室流程",
        sectionTitle: "A. Büroalltag und Krankmeldung",
        sectionTitleZh: "办公室流程与请病假",
        words: [
          ["die Abteilung", "organisatorischer Teil einer Firma", "部门"],
          ["die Arbeitsunfähigkeitsbescheinigung", "offizieller Nachweis über Krankheit", "病假证明"],
          ["das Attest", "ärztlicher Nachweis", "证明（医疗）"],
          ["der Auftrag", "konkrete Arbeitsaufgabe oder Bestellung", "任务；订单"],
          ["der/die Beschäftigte", "Person in einem Arbeitsverhältnis", "员工"],
          ["die Geschäftsführung", "Leitung eines Unternehmens", "公司管理层"],
          ["das Intranet", "internes digitales Firmennetz", "公司内网"],
          ["der Personalbogen", "Formular mit Personaldaten", "人事表"],
          ["der/die Vorgesetzte", "direkte Leitungsperson", "上级；主管"],
          ["absolvieren", "etwas planmäßig abschließen", "完成（课程/培训）"],
          ["sich abstimmen mit", "mit jemandem koordinieren", "与……协调"],
          ["sich besprechen mit", "mit jemandem etwas beraten", "与……商量"],
          ["erledigen", "zu Ende bringen", "完成；处理"],
          ["sich krankmelden", "mitteilen, dass man krank ist", "请病假"]
        ]
      },
      {
        id: "beratung-und-auswahl",
        tabLabel: "Service",
        tabLabelZh: "服务沟通",
        sectionTitle: "B. Beratung und Auswahl",
        sectionTitleZh: "推荐、咨询与客户沟通",
        words: [
          ["die Auswahl", "Menge möglicher Optionen", "选择"],
          ["das Tablet", "tragbarer Computer mit Touchscreen", "平板电脑"],
          ["anbieten", "jemandem etwas zur Wahl geben", "提供"],
          ["ansprechen", "ein Thema nennen oder Kontakt aufnehmen", "提及；沟通"],
          ["beraten", "fachlich empfehlen oder informieren", "咨询；建议"],
          ["sich beschweren bei", "bei jemandem eine Beschwerde äußern", "向……投诉"],
          ["empfehlen", "etwas als gut vorschlagen", "推荐"],
          ["fragen nach", "gezielt nach etwas fragen", "询问"],
          ["hängen", "in hängender Position sein", "悬挂"],
          ["legen", "etwas flach an einen Ort setzen", "放（平放）"],
          ["liegen", "sich an einem Ort befinden", "位于；放着"],
          ["nachschauen", "etwas kurz prüfen", "查看"],
          ["stellen", "etwas aufrecht an einen Ort setzen", "放（竖立）"],
          ["stehen", "aufrecht an einem Ort sein", "站立；放着"],
          ["bekannt für", "wegen etwas berühmt", "以……闻名"],
          ["individuell", "auf die einzelne Person angepasst", "个别的"],
          ["intensiv", "stark und konzentriert", "密集的"]
        ]
      }
    ]
  },
  {
    id: "ausbildung-technik-und-arbeitsmarkt",
    number: 7,
    title: "Ausbildung, Technik und Arbeitsmarkt",
    promptZh:
      "这一组把职业学校、设备说明和就业市场放在同一条学习线上。因为很多德语学习者会先经历培训与设备操作，再进入求职、转岗或继续深造。",
    promptEn:
      "This topic brings vocational training, device language and the labour market into one learning line. Many German learners first go through training and technical routines before they move into job search, retraining or further development.",
    sections: [
      {
        id: "ausbildung-im-betrieb",
        tabLabel: "Ausbildung",
        tabLabelZh: "培训与车间",
        sectionTitle: "A. Ausbildung im Betrieb",
        sectionTitleZh: "企业培训与工作交接",
        words: [
          ["der/die Ausbilder/in", "Person, die Auszubildende anleitet", "培训师"],
          ["das Ausbildungsjahr", "ein Jahr innerhalb der Ausbildung", "培训年"],
          ["der/die Auszubildende", "Person in beruflicher Ausbildung", "学徒"],
          ["die Berufsschule", "Schule parallel zur Ausbildung", "职业学校"],
          ["die Bestellung", "Auftrag zum Kaufen", "订单"],
          ["das Ersatzteil", "Teil zum Austausch", "备件"],
          ["der Feierabend", "Zeit nach der Arbeit", "下班时间"],
          ["die Übergabe", "Weitergabe an die nächste Person", "交接"],
          ["abholen", "etwas holen oder jemanden mitnehmen", "取；接"],
          ["besorgen", "etwas organisieren oder kaufen", "采购；办理"],
          ["einbauen", "in etwas einsetzen", "安装"],
          ["einstellen", "jemanden anstellen oder etwas justieren", "雇用"],
          ["kaputtgehen", "nicht mehr funktionieren", "坏掉"],
          ["los sein", "passieren oder stattfinden", "发生；有情况"],
          ["montieren", "Teile zusammenbauen", "组装"],
          ["reichen", "genug sein", "足够"],
          ["reparieren", "wieder funktionsfähig machen", "修理"],
          ["vorbeikommen", "kurz kommen oder besuchen", "顺便来"],
          ["stressig", "mit viel Belastung verbunden", "有压力的"]
        ]
      },
      {
        id: "geraete-und-sicherheit",
        tabLabel: "Technik",
        tabLabelZh: "设备与安全",
        sectionTitle: "B. Geräte und Sicherheit",
        sectionTitleZh: "设备、材料与安全提示",
        words: [
          ["die Bedienungsanleitung", "Anleitung für die Benutzung", "使用说明书"],
          ["das Gerät", "technische Maschine oder Apparat", "设备"],
          ["der Griff", "Teil zum Halten", "把手"],
          ["das Holz", "Material aus Bäumen", "木头"],
          ["das Merkmal", "typisches Kennzeichen", "特征"],
          ["das Metall", "festes technisches Material", "金属"],
          ["das Plastik", "künstlicher Kunststoff", "塑料"],
          ["der Schalter", "Teil zum Ein- und Ausschalten", "开关"],
          ["der Sicherheitshinweis", "wichtige Warnung zur Sicherheit", "安全提示"],
          ["die Steckdose", "Anschluss für Strom", "插座"],
          ["der Stecker", "Teil für den Stromanschluss", "插头"],
          ["der Stoff", "Material oder Gewebe", "材料"],
          ["bestellen", "etwas kaufen und liefern lassen", "订购"],
          ["einschalten", "ein Gerät anmachen", "打开（电源）"],
          ["abschalten", "ein Gerät ausmachen", "关闭（电源）"],
          ["es handelt sich um", "es geht um oder es ist", "涉及；是关于", "已按常用固定表达整理，原笔记中常写成 sich handeln um。"],
          ["formschön", "ästhetisch gestaltet", "造型美观的"],
          ["handlich", "leicht zu benutzen und zu tragen", "便于使用的"],
          ["leistungsstark", "mit hoher Leistung", "性能强的"],
          ["robust", "widerstandsfähig und stabil", "结实的"],
          ["stabil", "fest und sicher", "稳定的"]
        ]
      },
      {
        id: "neuorientierung-am-arbeitsmarkt",
        tabLabel: "Arbeitsmarkt",
        tabLabelZh: "就业市场",
        sectionTitle: "C. Neuorientierung am Arbeitsmarkt",
        sectionTitleZh: "就业市场与职业转向",
        words: [
          ["die Arbeitsagentur", "staatliche Stelle für Arbeitssuche", "就业局"],
          ["der Arbeitsmarkt", "Bereich von Angebot und Nachfrage nach Arbeit", "劳动力市场"],
          ["der Bereich", "abgegrenztes Fachgebiet", "领域"],
          ["die Umschulung", "berufliche Neuqualifizierung", "再培训"],
          ["arbeiten in", "in einem Bereich tätig sein", "在……工作"],
          ["sich auskennen mit", "gute Kenntnisse über etwas haben", "熟悉；精通"],
          ["sich informieren über", "Informationen sammeln über", "了解；查询"],
          ["sich orientieren", "eine neue Richtung finden", "重新定位方向"],
          ["sich verändern", "anders werden", "改变"],
          ["alternativ", "eine andere Möglichkeit bietend", "替代的"],
          ["besetzt sein", "schon belegt oder nicht frei", "已被占用"],
          ["digital", "elektronisch und datenbasiert", "数字化的"],
          ["gefragt", "stark nachgefragt", "受欢迎的"],
          ["nebenberuflich", "zusätzlich zum Hauptberuf", "兼职的"],
          ["regelmäßig", "in gleichen Abständen", "定期的"],
          ["aus gesundheitlichen Gründen", "wegen der Gesundheit", "出于健康原因"],
          ["gute Chancen auf dem Arbeitsmarkt", "gute Aussichten für eine Stelle", "在就业市场上有好机会"]
        ]
      }
    ]
  },
  {
    id: "unternehmen-und-empfang",
    number: 8,
    title: "Unternehmen und Empfang",
    promptZh:
      "这一组词围绕公司介绍、前台接待和跨部门沟通。先熟悉企业类型、总部和组织方式，再把接待、转达、谈判这些动作放进真实办公场景里练习。",
    promptEn:
      "This topic focuses on company profiles, reception work and internal coordination. Start with company types, headquarters and structures, then connect them with practical actions like greeting visitors, forwarding information and negotiating.",
    sections: [
      {
        id: "firmenprofil-und-empfang",
        tabLabel: "Firmenprofil",
        tabLabelZh: "公司与前台",
        sectionTitle: "A. Firmenprofil und Empfang",
        sectionTitleZh: "公司介绍与前台接待",
        words: [
          ["die Eigenschaft", "Merkmal oder charakteristische Qualität", "特征；品质"],
          ["die Einstellung", "innere Haltung oder technische Konfiguration", "态度；设置"],
          ["der Empfang", "Bereich für Begrüßung und Anmeldung", "接待；前台"],
          ["die Flexibilität", "Fähigkeit, sich gut anzupassen", "灵活性"],
          ["die Firma", "Unternehmen oder Betrieb", "公司"],
          ["die GmbH", "Gesellschaft mit beschränkter Haftung", "有限责任公司"],
          ["der Hauptsitz", "zentrale Niederlassung eines Unternehmens", "总部"],
          ["die IT", "Bereich der Informationstechnologie", "信息技术"],
          ["die Kenntnis", "Wissen oder Vertrautheit mit etwas", "知识；了解"],
          ["der Mitarbeiter", "Person, die in einem Unternehmen arbeitet", "员工"],
          ["das Organisationstalent", "besondere Fähigkeit zum Organisieren", "组织能力"],
          ["die Telefonanlage", "technisches System für Telefongespräche", "电话系统"],
          ["das Training", "gezielte praktische Schulung", "培训"],
          ["die Umgangsformen", "soziale Regeln für höfliches Verhalten", "礼仪；行为规范"],
          ["die Voraussetzung", "Bedingung, die erfüllt sein muss", "条件"],
          ["die Zentrale", "zentraler Sitz eines Unternehmens", "总部"],
          ["bedienen", "ein Gerät benutzen oder Kunden helfen", "操作；服务"],
          ["sich befinden", "an einem Ort liegen oder sein", "位于"],
          ["begrüßen", "jemanden freundlich willkommen heißen", "欢迎；问候"],
          ["gründen", "ein Unternehmen offiziell ins Leben rufen", "创立"],
          ["verbessern", "besser machen", "改善"],
          ["geduldig", "ruhig und ohne Eile", "有耐心的"],
          ["gepflegt", "ordentlich und sauber wirkend", "整洁的"],
          ["hilfsbereit", "bereit zu helfen", "乐于助人的"],
          ["international", "mehrere Länder betreffend", "国际的"],
          ["tätig", "beruflich aktiv", "从事工作的"],
          ["weltweit", "auf der ganzen Welt", "全球的"],
          ["die AG", "Aktiengesellschaft", "股份公司"],
          ["das Tochterunternehmen", "Unternehmen, das zu einem größeren Konzern gehört", "子公司"]
        ]
      },
      {
        id: "koordination-und-kommunikation",
        tabLabel: "Kommunikation",
        tabLabelZh: "协调沟通",
        sectionTitle: "B. Koordination und Kommunikation",
        sectionTitleZh: "协调、转达与商务沟通",
        words: [
          ["kennzeichnen", "deutlich markieren oder beschriften", "标记；标识"],
          ["organisieren", "planen und strukturieren", "组织"],
          ["prüfen", "sorgfältig kontrollieren", "检查"],
          ["verhandeln mit", "mit jemandem über Bedingungen sprechen", "与……谈判"],
          ["weiterleiten", "an eine andere Person oder Stelle senden", "转发"],
          ["zusammenarbeiten mit", "gemeinsam mit jemandem arbeiten", "与……合作"],
          ["einwandfrei", "ohne Fehler oder Mängel", "无缺陷的；完美的"],
          ["verantwortlich für", "für etwas die Verantwortung tragen", "负责……"],
          ["zuständig für", "offiziell für etwas verantwortlich sein", "负责……"],
          ["kaufmännisch", "den Handel oder die Wirtschaft betreffend", "商业的；经济的"],
          ["unter anderem", "zum Beispiel und nicht nur", "其中包括"]
        ]
      },
      {
        id: "anreise-und-besprechung",
        tabLabel: "Reisetermine",
        tabLabelZh: "出差与会面",
        sectionTitle: "C. Anreise und Besprechung",
        sectionTitleZh: "出差、抵达与客户会面",
        words: [
          ["die Anreise", "Weg oder Reise zu einem Ziel", "到达；抵达"],
          ["die Besprechung", "Treffen zum Austausch über Arbeit", "会议"],
          ["der Flug", "Reise mit dem Flugzeug", "航班"],
          ["die Heimreise", "Rückreise nach Hause", "返程"],
          ["der Neukunde", "Kunde, der neu hinzugekommen ist", "新客户"],
          ["anreisen", "zu einem Ort kommen", "到达；抵达"],
          ["Bescheid sagen", "jemanden informieren", "告知"],
          ["eintreffen", "an einem Ort ankommen", "到达"],
          ["informieren", "jemanden über etwas in Kenntnis setzen", "通知；告知"],
          ["verlaufen", "sich in bestimmter Weise entwickeln", "进行；进展"],
          ["potenziell", "möglich oder denkbar", "潜在的"],
          ["reibungslos", "ohne Probleme oder Störungen", "顺利的"]
        ]
      }
    ]
  },
  {
    id: "duales-studium-und-berufsstart",
    number: 9,
    title: "Duales Studium und Berufsstart",
    promptZh:
      "双元制学习、实习实践和正式进入职场，常常在同一条成长线上。把理论、实践和财务岗位词一起学，会更容易理解德语里职业路径的表达方式。",
    promptEn:
      "Dual study programs, practical phases and the first steps into working life often belong to the same development path. Learning theory, practice and finance vocabulary together makes career-related German much easier to understand.",
    sections: [
      {
        id: "theorie-und-praxis",
        tabLabel: "Theorie & Praxis",
        tabLabelZh: "理论与实践",
        sectionTitle: "A. Theorie und Praxis",
        sectionTitleZh: "理论与实践交替",
        words: [
          ["die Praxis", "praktische Anwendung im echten Alltag", "实践"],
          ["der/die Studierende", "Person, die an einer Hochschule studiert", "大学生"],
          ["die Theorie", "gedankliches oder wissenschaftliches Wissen", "理论"],
          ["der Vorteil", "positive Seite oder Nutzen", "优点；优势"],
          ["sich abwechseln", "nacheinander im Wechsel stattfinden", "轮流；交替"],
          ["erstellen", "etwas gezielt anfertigen", "制作；创建"],
          ["in Rente gehen", "das Berufsleben beenden", "退休"],
          ["rechnen", "Zahlen berechnen oder kalkulieren", "计算"],
          ["akademisch", "die Hochschule oder Wissenschaft betreffend", "学术的"],
          ["gemeinsam", "zusammen mit anderen", "共同的"]
        ]
      },
      {
        id: "finanzen-und-qualifikation",
        tabLabel: "Finanzen",
        tabLabelZh: "财务与资历",
        sectionTitle: "B. Finanzen und Qualifikation",
        sectionTitleZh: "财务岗位与专业资历",
        words: [
          ["die Arbeitskraft", "personelle Fähigkeit zu arbeiten", "劳动力"],
          ["die Berufsakademie", "Hochschule mit starkem Praxisbezug", "职业学院"],
          ["der Betriebswirt", "Fachperson für betriebswirtschaftliche Aufgaben", "企业管理人员"],
          ["die Buchhaltung", "Bereich für finanzielle Aufzeichnungen", "会计"],
          ["der Finanzbuchhalter", "Fachperson für die Finanzbuchhaltung", "财务会计"],
          ["der Konzern", "großes Unternehmen mit mehreren Firmen", "集团公司"],
          ["der Monats-/Jahresabschluss", "finanzieller Abschluss eines Monats oder Jahres", "月度/年度结算"],
          ["der Nachteil", "negative Seite oder Schwäche", "缺点"],
          ["die Phase", "bestimmter Abschnitt in einem Prozess", "阶段"]
        ]
      },
      {
        id: "arbeitsleben-und-einstieg",
        tabLabel: "Berufsstart",
        tabLabelZh: "职业起步",
        sectionTitle: "C. Arbeitsleben und Einstieg",
        sectionTitleZh: "职业生活与进入职场",
        words: [
          ["das Arbeitsleben", "gesamte berufliche Lebensphase", "职业生活"],
          ["der Ausbildungsberuf", "Beruf, den man in einer Ausbildung lernt", "培训职业"],
          ["der/die Auszubildende", "Person in einer beruflichen Ausbildung", "学徒"],
          ["der/die Azubi", "umgangssprachlich für Auszubildende", "学徒（口语）"],
          ["der Berufseinstieg", "Beginn des beruflichen Lebens", "进入职场"],
          ["die Berufsschule", "Schule parallel zur Ausbildung", "职业学校"],
          ["der Schulabschluss", "offizieller Abschluss an einer Schule", "毕业证书"],
          ["erbringen", "eine Leistung liefern oder erfüllen", "提供；完成"],
          ["dual", "mit zwei Lernorten oder Systemen", "双元制的"]
        ]
      }
    ]
  },
  {
    id: "arbeitsalltag-und-regelungen",
    number: 10,
    title: "Arbeitsalltag und Regelungen",
    promptZh:
      "真正入职以后，最常见的不是抽象词，而是和工作日流程、办公室规则、请假、观察、沟通有关的表达。把这些串起来，最适合做情境复盘。",
    promptEn:
      "After actually starting a job, the most useful vocabulary is not abstract but connected to routines, office rules, leave, observation and communication. These expressions work especially well in realistic workplace scenarios.",
    sections: [
      {
        id: "erster-arbeitstag",
        tabLabel: "Arbeitstag",
        tabLabelZh: "第一天与印象",
        sectionTitle: "A. Erster Arbeitstag",
        sectionTitleZh: "工作日、印象与适应",
        words: [
          ["das Arbeitsklima", "Atmosphäre im Team oder am Arbeitsplatz", "工作氛围"],
          ["der Arbeitstag", "Tag mit beruflichen Aufgaben", "工作日"],
          ["das Bürogebäude", "Gebäude, in dem Büros untergebracht sind", "办公楼"],
          ["der Eindruck", "Wirkung, die etwas auf jemanden macht", "印象"],
          ["die Person", "ein Mensch oder eine Einzelperson", "人"],
          ["der Rundgang", "gemeinsamer kurzer Weg zur Besichtigung", "参观；巡视"],
          ["der Zeitdruck", "Druck wegen knapper Zeit", "时间压力"],
          ["eine Stelle antreten", "eine neue Arbeit beginnen", "入职"],
          ["einen Eindruck machen", "eine Wirkung hinterlassen", "留下印象"],
          ["bei", "an einem Ort oder bei einer Person", "在……（某人处）"],
          ["gekleidet", "in bestimmter Weise angezogen", "穿着……的"],
          ["bis auf Weiteres", "vorläufig, bis es neue Informationen gibt", "暂时；直到另行通知"]
        ]
      },
      {
        id: "pflichten-und-unterlagen",
        tabLabel: "Regeln",
        tabLabelZh: "规则与文件",
        sectionTitle: "B. Pflichten und Unterlagen",
        sectionTitleZh: "规则、权利与必备文件",
        words: [
          ["die Mittagspause", "Pause am Mittag", "午休"],
          ["die Motivation", "innerer Antrieb", "动力"],
          ["die Pausenregelung", "Vorschrift zu den Pausen", "休息规定"],
          ["die Pflicht", "etwas, das man tun muss", "义务"],
          ["der Ratschlag", "gut gemeinter Hinweis", "建议"],
          ["das Recht", "berechtigter Anspruch", "权利"],
          ["die Regelung", "konkrete Vorschrift oder Ordnung", "规定"],
          ["der Sozialversicherungsausweis", "offizieller Nachweis für die Sozialversicherung", "社保证明"],
          ["die Spielregel", "vereinbarte Regel im gemeinsamen Umgang", "规则"],
          ["die Steueridentifikationsnummer", "offizielle persönliche Steuernummer", "税号"],
          ["der Tarifvertrag", "kollektiver Arbeitsvertrag", "集体合同"],
          ["die Überstunde", "zusätzliche Arbeitsstunde", "加班"],
          ["die Unterlagen", "Dokumente oder Materialien", "材料；文件"],
          ["die Verwaltung", "administrativer Bereich", "行政管理"],
          ["der/die Vorgesetzte", "Person mit Führungsverantwortung", "上级；主管"]
        ]
      },
      {
        id: "verhalten-und-ablauf",
        tabLabel: "Verhalten",
        tabLabelZh: "行为与流程",
        sectionTitle: "C. Verhalten und Ablauf",
        sectionTitleZh: "行为规范与工作流程",
        words: [
          ["ankommen auf", "von etwas abhängen", "取决于"],
          ["sich anpassen an", "sich auf etwas einstellen", "适应"],
          ["beantworten", "eine Frage oder Nachricht erwidern", "回答"],
          ["beobachten", "genau hinsehen", "观察"],
          ["berücksichtigen", "etwas mitbedenken", "考虑到"],
          ["bestehen", "vorhanden sein oder andauern", "存在；成立"],
          ["erwarten", "mit etwas rechnen", "期待"],
          ["einen Ratschlag geben", "einen hilfreichen Hinweis formulieren", "提出建议"],
          ["genehmigen", "offiziell erlauben", "批准"],
          ["sich halten an", "eine Regel befolgen", "遵守"],
          ["Augen und Ohren offen halten", "aufmerksam und wachsam bleiben", "保持警觉"],
          ["nachfragen wegen", "noch einmal gezielt fragen", "询问"],
          ["regeln", "ordnen oder festlegen", "规定；处理"],
          ["umgehen mit", "etwas handhaben", "应对"],
          ["zugehen auf", "sich annähern oder auf jemanden aktiv zugehen", "接近；走向"],
          ["interessiert", "mit echtem Interesse", "感兴趣的"],
          ["sachlich", "nüchtern und objektiv", "客观的"],
          ["verbindlich", "zuverlässig und klar zugesagt", "有约束力的；可靠的"],
          ["der Ablauf", "zeitliche oder inhaltliche Reihenfolge", "流程"],
          ["die Anweisung", "klare Vorgabe", "指示"],
          ["das Notwendige", "alles, was nötig ist", "必要的事情"],
          ["die Regel", "allgemeine Vorschrift", "规则"],
          ["besprechen", "gemeinsam über etwas sprechen", "讨论"],
          ["unterstützen", "Hilfe leisten", "支持"],
          ["frühzeitig", "rechtzeitig und nicht zu spät", "提前地"],
          ["zeitlich", "die Zeit betreffend", "时间上的"]
        ]
      }
    ]
  },
  {
    id: "bewerbung-und-lebenslauf-vertiefung",
    number: 11,
    title: "Bewerbung und Lebenslauf Vertiefung",
    promptZh:
      "这一组是求职进阶词，不只是面试两个字，而是从简历信息、书面表达、招聘广告到零售岗位要求，把整个求职链条连起来。",
    promptEn:
      "This topic deepens job-application vocabulary. It covers not only interviews, but also CV information, written application language, job ads and the requirements of retail positions along the whole application process.",
    sections: [
      {
        id: "lebenslauf-und-daten",
        tabLabel: "Lebenslauf",
        tabLabelZh: "简历信息",
        sectionTitle: "A. Lebenslauf und Daten",
        sectionTitleZh: "简历、信息与个人资料",
        words: [
          ["der Lebenslauf", "tabellarische Übersicht über Ausbildung und Beruf", "简历"],
          ["die Daten", "Informationen oder Angaben", "数据；信息"],
          ["das Geburtsdatum", "Tag der Geburt", "出生日期"],
          ["der Geburtsort", "Ort der Geburt", "出生地"],
          ["die Staatsangehörigkeit", "rechtliche Zugehörigkeit zu einem Staat", "国籍"],
          ["die Schulbildung", "schulischer Bildungsweg", "学历"],
          ["die Ausbildung", "berufliche Qualifizierung", "培训"],
          ["der Abschluss", "offizielles Ende einer Ausbildung oder Schule", "毕业证书"],
          ["die Berufserfahrung", "Erfahrung aus bisheriger Arbeit", "工作经验"],
          ["die Sprachkenntnisse", "Kenntnisse in einer Sprache", "语言能力"],
          ["die Muttersprache", "erste Sprache einer Person", "母语"],
          ["die Fortbildung", "berufliche Weiterbildung", "进修"],
          ["die Verkaufsabrechnung", "Abrechnung über Verkäufe", "销售结算"],
          ["das Bildungszentrum", "Einrichtung für Bildung und Kurse", "教育中心"],
          ["die Warenkunde", "Wissen über Produkte und Waren", "商品知识"],
          ["die Qualifizierung", "berufliche Befähigung oder Zertifizierung", "资格认证"],
          ["das Personalbüro", "Büro für Personalangelegenheiten", "人事办公室"],
          ["das Bewerbungsschreiben", "schriftlicher Bewerbungstext", "求职信"],
          ["das Telefonat", "mündliches Gespräch am Telefon", "电话通话"],
          ["der/die Bekannte", "Person, die man kennt", "熟人"],
          ["das Vorstellungsgespräch", "Gespräch zur Bewerbung auf eine Stelle", "面试"],
          ["die Bescheinigung", "offizielles Nachweisdokument", "证明"],
          ["der Discounter", "Geschäft mit eher günstigen Preisen", "折扣店"],
          ["die Bewerbungsmappe", "Sammlung aller Bewerbungsunterlagen", "求职资料夹"]
        ]
      },
      {
        id: "anschreiben-und-formulierung",
        tabLabel: "Formulierung",
        tabLabelZh: "书写表达",
        sectionTitle: "B. Anschreiben und Formulierung",
        sectionTitleZh: "求职表达与书写质量",
        words: [
          ["sich bewerben", "eine Bewerbung schicken", "申请"],
          ["recherchieren", "gezielt Informationen suchen", "查资料"],
          ["persönlich", "die eigene Person betreffend", "个人的"],
          ["mündlich", "gesprochen und nicht geschrieben", "口头的"],
          ["schriftlich", "in geschriebener Form", "书面的"],
          ["speziell", "besonders oder gezielt", "特别的"],
          ["beruflich", "den Beruf betreffend", "职业的"],
          ["die Abschlussnote", "Note am Ende einer Ausbildung oder Schule", "毕业成绩"],
          ["die Anforderung", "konkrete Voraussetzung oder Erwartung", "要求"],
          ["die Berufsausbildung", "Ausbildung für einen bestimmten Beruf", "职业培训"],
          ["das Bewerbungsfoto", "Foto für eine Bewerbung", "证件照"],
          ["das Bewerbungsgespräch", "Gespräch im Rahmen einer Bewerbung", "面试"],
          ["die Grundkenntnisse", "erste grundlegende Kenntnisse", "基础知识"],
          ["die Note", "Bewertung einer Leistung", "成绩"],
          ["der Personaler", "Person aus dem Personalbereich", "人事人员"],
          ["die persönlichen Daten", "private Grundinformationen einer Person", "个人信息"],
          ["die Rechtschreibung", "korrekte Schreibweise", "拼写"],
          ["die Richtigkeit", "Korrektheit oder Genauigkeit", "正确性"],
          ["die Wahrscheinlichkeit", "Grad der Möglichkeit", "可能性"],
          ["anpassen an", "etwas auf etwas abstimmen", "适应"],
          ["beherrschen", "sicher können oder meistern", "掌握"],
          ["versehen mit", "mit etwas ausstatten", "配有"],
          ["verfassen", "einen Text schreiben", "撰写"],
          ["formal", "einer Form entsprechend und offiziell", "正式的"],
          ["übersichtlich", "klar gegliedert und gut lesbar", "清晰的"],
          ["seriös", "zuverlässig und glaubwürdig", "严肃的；可靠的"],
          ["unseriös", "nicht vertrauenswürdig", "不可靠的"],
          ["professionell", "fachlich und korrekt", "专业的"],
          ["eigenhändig", "mit eigener Hand oder persönlich", "亲自的"]
        ]
      },
      {
        id: "stellenanzeige-und-handel",
        tabLabel: "Stellenanzeige",
        tabLabelZh: "招聘与零售",
        sectionTitle: "C. Stellenanzeige und Handel",
        sectionTitleZh: "招聘广告与零售岗位",
        words: [
          ["die Stellenanzeige", "öffentliche Anzeige für eine freie Stelle", "招聘广告"],
          ["das Delikatessengeschäft", "Geschäft für feine Lebensmittel", "食品专卖店"],
          ["der Einzelhandel", "Verkauf direkt an Kundinnen und Kunden", "零售业"],
          ["die Beratung", "fachliche Unterstützung oder Empfehlung", "咨询"],
          ["ab sofort", "direkt von jetzt an", "立即"],
          ["idealerweise", "am besten oder im besten Fall", "理想情况下"],
          ["die Anlage", "beigefügtes Dokument", "附件"],
          ["der Betreff", "Titel oder Thema eines Schreibens", "主题"],
          ["die Annahme", "Akzeptanz oder Aufnahme", "录用；接受"],
          ["die Stärke", "besondere positive Fähigkeit", "优点"],
          ["die Probezeit", "erste Arbeitsphase zum Kennenlernen", "试用期"],
          ["ausfüllen", "ein Formular mit Daten ergänzen", "填写"],
          ["erforderlich", "notwendig oder notwendig vorgeschrieben", "必要的"],
          ["anschließend", "danach oder im nächsten Schritt", "随后"],
          ["die Vorliebe", "persönliche Präferenz", "偏好"],
          ["die Fähigkeit", "praktisches Können", "能力"],
          ["die Ware", "Produkt zum Verkauf", "商品"],
          ["die Qualifikation", "fachliche Eignung", "资格"],
          ["die Erfahrung", "praktisch erworbenes Wissen", "经验"],
          ["die Teamfähigkeit", "Fähigkeit zur Zusammenarbeit im Team", "团队能力"],
          ["der Einzelhandelskaufmann", "männliche Fachkraft im Einzelhandel", "零售商人"],
          ["die Einzelhandelskauffrau", "weibliche Fachkraft im Einzelhandel", "女零售商人"],
          ["der Leiter", "männliche Führungsperson", "负责人"],
          ["die Leiterin", "weibliche Führungsperson", "女负责人"],
          ["die Lebensmittelabteilung", "Bereich für Lebensmittel im Geschäft", "食品部门"],
          ["das Kaufhaus", "großes Warenhaus", "百货公司"],
          ["der Erziehungsurlaub", "ältere Bezeichnung für Elternzeit", "育儿假"],
          ["die Kette", "Gruppe zusammengehöriger Filialen", "连锁店"],
          ["die Hilfskraft", "unterstützende Arbeitskraft", "助手"],
          ["die Chance", "gute Möglichkeit", "机会"],
          ["richten an", "an jemanden adressieren", "寄给；面向"],
          ["fachkundig", "mit viel Fachwissen", "专业的"],
          ["erfolgreich", "mit gutem Ergebnis", "成功的"],
          ["üblich", "allgemein normal oder verbreitet", "常见的"],
          ["vollkommen", "ganz und vollständig", "完全的"],
          ["flexibel", "gut anpassbar", "灵活的"],
          ["überqualifiziert", "mit mehr Qualifikation als nötig", "资历过高的"],
          ["geeignet für", "passend für etwas", "适合"]
        ]
      }
    ]
  },
  {
    id: "unternehmen-und-abteilungen",
    number: 12,
    title: "Unternehmen und Abteilungen",
    promptZh:
      "当你要介绍一家公司时，德语会很快进入‘部门、采购、生产、研发、市场、供应商’这些结构化词汇。把它们按组织图来学，记忆会清楚很多。",
    promptEn:
      "When you describe a company, German quickly moves into structured vocabulary such as departments, purchasing, production, development, marketing and suppliers. Learning these words through an organisational chart makes them much easier to retain.",
    sections: [
      {
        id: "struktur-und-abteilungen",
        tabLabel: "Struktur",
        tabLabelZh: "组织结构",
        sectionTitle: "A. Struktur und Abteilungen",
        sectionTitleZh: "组织结构与部门名称",
        words: [
          ["die Abteilung", "organisatorischer Teil eines Unternehmens", "部门"],
          ["das Betriebsklima", "Atmosphäre im Betrieb", "工作氛围"],
          ["der Einkauf", "Bereich für Beschaffung", "采购"],
          ["die Entwicklung", "Bereich für neue Lösungen oder Forschung", "发展；研发"],
          ["die Finanzen", "Bereich für Geld und Budget", "财务"],
          ["die Geschäftsleitung", "oberes Management eines Unternehmens", "管理层"],
          ["die Herstellung", "Produktion von Waren", "生产"],
          ["das Marketing", "Bereich für Markt und Werbung", "市场营销"],
          ["das Organigramm", "grafische Darstellung der Organisationsstruktur", "组织结构图"],
          ["das Personal", "Mitarbeitende eines Unternehmens", "员工；人事"],
          ["die Personalabteilung", "Abteilung für Personalfragen", "人事部门"],
          ["die Produktion", "Bereich, in dem Produkte hergestellt werden", "生产"],
          ["der Rohstoff", "Material für die Herstellung", "原材料"],
          ["die Struktur", "innerer Aufbau eines Systems", "结构"],
          ["das Unternehmen", "Firma oder Betrieb", "公司；企业"],
          ["der Vertrieb", "Bereich für Verkauf und Absatz", "销售"],
          ["die Werbekampagne", "geplante Werbeaktion", "广告活动"],
          ["der Zulieferer", "Firma, die Material oder Teile liefert", "供应商"]
        ]
      },
      {
        id: "prozesse-und-aufbau",
        tabLabel: "Prozesse",
        tabLabelZh: "流程与建设",
        sectionTitle: "B. Prozesse und Aufbau",
        sectionTitleZh: "流程、建设与发展动作",
        words: [
          ["achten auf", "auf etwas bewusst achten", "注意"],
          ["aufbauen", "schrittweise errichten oder entwickeln", "建立"],
          ["benötigen", "etwas brauchen", "需要"],
          ["sich beschäftigen mit", "sich mit etwas inhaltlich befassen", "从事；研究"],
          ["einstellen", "jemanden anstellen", "雇用"],
          ["entwickeln", "neu gestalten oder verbessern", "发展；开发"]
        ]
      }
    ]
  }
];
